# Generated by Django 4.2.30 on 2026-09-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Demografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Editorial')),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True, verbose_name='País de Origen')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('sinopsis', models.TextField(blank=True, null=True, verbose_name='Sinopsis')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('PAUSA', 'En pausa')], default='EN_CURSO', max_length=20, verbose_name='Estado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='mangaAPP.autor', verbose_name='Autor')),
                ('demografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='mangaAPP.demografia', verbose_name='Demografía')),
            ],
        ),
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tomo', models.PositiveIntegerField(verbose_name='Número de Tomo')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('archivo_portada', models.FileField(upload_to='portadas/', verbose_name='Archivo/Portada')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomos', to='mangaAPP.editorial', verbose_name='Editorial')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomos', to='mangaAPP.serie', verbose_name='Serie')),
            ],
        ),
    ]
