# Generated by Django 4.2.30 on 2026-09-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='tomo_portada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_portada', to='mangaApp.tomo', verbose_name='Tomo para Portada'),
        ),
    ]
